force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TeamMembersController.cls
public with sharing class TeamMembersController {
    
    //https://developer.salesforce.com/forums/?id=9062I000000IE4kQAG
    //@AuraEnabled(Cacheable=true)
    @AuraEnabled
    public static void saveTeamMembers(String teamId, List<String> contactIds) {
        
        try{
            List<Team_Member__c> newTeamMembers = new List<Team_Member__c>();

            for(String conId : contactIds) {
                Team_Member__c newTeamMember = new Team_Member__c(
                    Team__c = teamId,
                    Contact__c = conId
                );
                newTeamMembers.add(newTeamMember);
            }

            List<Database.SaveResult> saveResults = Database.insert(newTeamMembers, false);
        } catch(Exception e) {
            System.debug(e);
        }
    }
}